from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class TaskDocScaffoldRequest:
    task_dir: Path
    goal: str
    source_request: str
    workspace: Path

    @property
    def task_slug(self) -> str:
        return self.task_dir.name


def _contract_text(request: TaskDocScaffoldRequest) -> str:
    return f"""[Task Spec / Success Contract]

Task Metadata:
- Task slug: `{request.task_slug}`
- Source request: {request.source_request}
- Source of truth:
  - `{request.workspace / "AGENTS.md"}`
  - `{request.workspace / "README.md"}`

Goal:
- {request.goal}

Desired Effect:
- 为 `{request.task_slug}` 建立可执行的任务文档基线，便于后续补充具体实现范围。

Scope:
- 根据实际任务补充

Non-goals:
- 不在脚手架阶段直接修改代码

Deliverables:
- `contract.md`
- `prompt.md`
- `plan.md`
- `implement.md`
- `documentation.md`
- `status.md`

Change-Unit Inventory:
- `CHG-1`
  - Target: 待补充
  - Change: 待补充
  - Expected effect: 待补充
  - Risk: 待补充

Done When:
- `DW-1` 任务文档六件套建立完成。
- `DW-2` `check_task_docs.py` 对该任务目录通过。

Traceability:
- `CHG-1` -> `DW-1`, `DW-2`

Interface / Method Coverage Inventory:
- `COV-1`
  - Surface: 待补充
  - Methods / functions: 待补充
  - Behavior under test: 待补充
  - Linked test cases: `TC-1`

Test-Case Inventory:
- `TC-1`
  - Scenario: 任务文档脚手架生成并通过基础自检。
  - Trigger: 运行 `scripts/init_task_docs.py`。
  - Expected result: `contract/plan/status` 满足 `check_task_docs.py` 约束，其他三份文档存在。
  - Unit test: 待补充
  - Business test: `python scripts/check_task_docs.py {request.task_dir}`

Validation:
- `python scripts/check_task_docs.py {request.task_dir}`

Review Gates:
- 根据具体任务补充
"""


def _plan_text(request: TaskDocScaffoldRequest) -> str:
    return f"""Source of truth:
- `{request.task_dir / "contract.md"}`
- `{request.workspace / "AGENTS.md"}`
- `{request.workspace / "README.md"}`

Goal summary:
- {request.goal}

## M1
Scope:
- 补齐具体成功标准、影响文件、验证策略。

Change units:
- `CHG-1`
  - Effect: 将脚手架内容替换成任务真实范围。
  - Acceptance: `contract.md` / `status.md` / `plan.md` 与任务一致。
  - Linked test cases: `TC-1`

Acceptance:
- 任务文档可以作为真实 source of truth。

Validation:
- `python scripts/check_task_docs.py {request.task_dir}`
"""


def _status_text(request: TaskDocScaffoldRequest) -> str:
    return f"""Status: scaffolded

Current phase:
- Documentation bootstrap

Document self-check gate status:
- Pending

Latest update:
- Generated by `scripts/init_task_docs.py`
- Goal: {request.goal}

Change-unit status:
- `CHG-1`: pending

Validation log:
- Pending

Blockers:
- None
"""


def _prompt_text(request: TaskDocScaffoldRequest) -> str:
    return f"""- Task Name / 任务名: {request.task_slug}
- Task Slug / 任务目录名: {request.task_slug}
- Workspace / 工作区: {request.workspace}
- Source of truth:
  - `{request.task_dir / "contract.md"}`
  - `{request.task_dir / "plan.md"}`
  - `{request.workspace / "AGENTS.md"}`
  - `{request.workspace / "README.md"}`

- Goal summary / 目标摘要:
  - {request.goal}

- Current milestone / 当前里程碑:
  - `M1`

- Active focus / 当前焦点:
  - 将脚手架内容替换为任务真实范围和验证。
"""


def _implement_text(request: TaskDocScaffoldRequest) -> str:
    return f"""- Metadata:
  - Task: `{request.task_slug}`
  - Source of truth: `contract.md`, `plan.md`, `status.md`, `documentation.md`

- Execution rules:
  - 先补齐 task docs，再开始代码改动。
  - 每次进入新里程碑前更新 `status.md` 与 `documentation.md`。

- Verification baseline:
  - `python scripts/check_task_docs.py {request.task_dir}`
"""


def _documentation_text(request: TaskDocScaffoldRequest) -> str:
    return f"""Current phase:
- scaffolded

Active milestone:
- `M1`

Document self-check gate status:
- Pending

Most recent update:
- Generated by `scripts/init_task_docs.py`
- Goal: {request.goal}

Completed work:
- 创建 `contract.md`
- 创建 `plan.md`
- 创建 `status.md`
- 创建 `prompt.md`
- 创建 `implement.md`
- 创建 `documentation.md`

In-progress work:
- 等待任务所有者补齐真实范围

Change-unit status:
- `CHG-1`: pending

Validation log:
- Pending

Blockers:
- None
"""


def build_task_docs(request: TaskDocScaffoldRequest) -> dict[str, str]:
    return {
        "contract.md": _contract_text(request),
        "plan.md": _plan_text(request),
        "status.md": _status_text(request),
        "prompt.md": _prompt_text(request),
        "implement.md": _implement_text(request),
        "documentation.md": _documentation_text(request),
    }


def scaffold_task_docs(request: TaskDocScaffoldRequest, *, force: bool = False) -> list[Path]:
    task_dir = request.task_dir.resolve()
    task_dir.mkdir(parents=True, exist_ok=True)
    payloads = build_task_docs(request)
    written: list[Path] = []
    for filename, content in payloads.items():
        target = task_dir / filename
        if target.exists() and not force:
            raise FileExistsError(f"Target file already exists: {target}")
        target.write_text(content, encoding="utf-8")
        written.append(target)
    return written
